name: pull_request_flow10
on: 
  pull_request:
    types:
    - opened
    branches:
    - deletebranch4
jobs:
  testscript:
    runs-on: ubuntu-latest
    steps:
      - name: checkoutut
        run: echo "Hello world"
      