name: demoworkflow
on: push
jobs:
  mytest:
    runs-on: ubuntu-latest
    steps:
    - name: Update package
      run: sudo apt-get update -y
    - name: test
      run: echo "Hello" >> testfile
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: testfile
        path: testfile

  mytest2:
    runs-on: ubuntu-latest
    needs: mytest
    steps:
    - name: Show me file content
      uses: actions/download-artifact@v3
      with:
        name: testfile
    - name: Cat it
      run: cat testfile
      