name: pull_request_flow11
on: 
  push:
  pull_request:
    types:
    - opened
    branches:
    - main
jobs:
  testscript:
    runs-on: ubuntu-latest
    steps:
      - name: checkoutut
        run: echo "Hello world"
      